### PR TITLE
 New features

### PR DESCRIPTION
**Pull request by jogibear9988**
- Configuration for Expression Parsing
- new for named Types

### CODE REVIEW

**Comment by jogibear9988** [comment]
Is this patch mergeable?

**Comment by StefH** [comment]
Whats the difference between this and `https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/GlobalConfig.cs`?

**Comment by jogibear9988** [comment]
That GlobalConfig is static! If I use dynamiclinq within different assemblies, I can not have a different configuration!

**Comment by StefH** [comment]
I did add a small comment in GetTypeInfo.

And I still need to review more code in this patch.

**Comment by jogibear9988** [comment]
do I need to fix smth?

**Comment by StefH** [comment]
smth?

**Comment by jogibear9988** [comment]
something?

**Comment by StefH** [comment]
You can fix my comment on `type.GetTypeInfo().BaseType`

**Comment by jogibear9988** [comment]
I do not find it!

**Comment by StefH** [comment]
Sorry. Please check again.

**Comment by jogibear9988** [comment]
lokk at https://msdn.microsoft.com/de-de/library/system.reflection.ireflectabletype.gettypeinfo(v=vs.110).aspx
it's there since net 4.5

**Comment by jogibear9988** [comment]
And you still compile for net 4.0 so it is needed

**Comment by jogibear9988** [comment]
could you create a new nuget?

**Comment by StefH** [comment]
I found an error : 

`private readonly ParsingConfig _parsingConfig;`

_parsingConfig is never assigned a value

I'm fixing this now.

**Comment by StefH** [comment]
Uploaded new NuGet

**Pull request merged**
