### PR TITLE
Fix parsing config

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by StefH** [comment]
AppVeyor fails:

```
Starting test execution, please wait...
[xUnit.net 00:00:04.3455977]   Discovering: EntityFramework.DynamicLinq.Tests
[xUnit.net 00:00:04.9032123]   Discovered:  EntityFramework.DynamicLinq.Tests
[xUnit.net 00:00:04.9206366]   Starting:    EntityFramework.DynamicLinq.Tests
The active test run was aborted. Reason: Process is terminated due to StackOverflowException.
Total tests: Unknown. Passed: 9. Failed: 0. Skipped: 0.
```

**Comment by jogibear9988** [comment]
Yes... looking wich test fails... Problem is they don't run on my computer...

**Comment by jogibear9988** [comment]
@StefH is it ok now?

**Comment by StefH** [comment]
Appveyor is fine. I still need to review the code.

**Comment by StefH** [comment]
Is this PR still valid ? Or do I need to checkout the other one from you?

**Comment by jogibear9988** [comment]
do I need to fix smth?

**Comment by jogibear9988** [comment]
Is the fix okay?

**Comment by StefH** [comment]
I still have to review this change.

**Comment by jogibear9988** [comment]
could I help, so we get this merged?

**Comment by jogibear9988** [comment]
I could not merge, only you can 😊

**Pull request merged**
