### PR TITLE
Feature: Add support for querying a IQueryable<dynamic>

### PR DESCRIPTION
**Pull request by NickDarvey**
Updates the `ParseMemberAccess` method so that if it can't get the property or field, it tries getting the member by a dynamic operation or by an indexer operation.

After a lot of searching I ended up on [this bit of code](https://github.com/dkackman/SqlLinq/blob/210b594e37f14061424397368ed750ce547c21e7/SqlLinq/SyntaxTree/ExpressionFactory.cs#L114) which seems to do the trick. The `ExpressionTests_Select_ExpandoObjects` test passes now.

Some notes:
- It will throw an exception only during evaluation if it can't find the specified member (and it is an `object` or has an indexer), currently a `InvalidOperationException` but perhaps introducing a new exception type is warranted?
- I'd still like to get `ExpressionTests_Select_DynamicObjects` but I'm not sure how I'll go.
- @StefH: Are you able to pull this and run all the tests on your machine? I was only able to get the solution building with a lot of hacking of projects and stripping out all platforms except net461.

### CODE REVIEW

**Comment by NickDarvey** [comment]
Oh sweet! CI! Okay, will take a look at which platform is dying...

**Comment by NickDarvey** [comment]
Oh, also tagging #136

**Comment by NickDarvey** [comment]
Ah, okay, it's failing to build `System.Linq.Dynamic.Core.Tests.csproj` because `System.Linq.Expressions.Expression.Dynamic Method (CallSiteBinder, Type, IEnumerable<Expression>)` is not available in `netcoreapp1.1`

What do you think about changing the test project to target `netcoreapp2.0` (which has the method is available) and make this feature conditional and only available for `netstandard2.0` platforms?

**Comment by StefH** [comment]
I'll take your PR and take a look.

**Comment by NickDarvey** [comment]
Alright, `ExpressionTests_Select_DynamicObjects` might need to come in another PR... Can this get merged in without it?

**Comment by StefH** [comment]
I will merge this code (at this point) to main and create a new NuGet. The discussion on other possible solutions will be done into the issue [https://github.com/StefH/System.Linq.Dynamic.Core/issues/136].

**Pull request merged**
