### PR TITLE
Support strings as Enum Parameter Objects

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
I can only compile net 4.5 on my system, and this works. hopefully you can help to fix the other?

**Comment by StefH** [comment]
1]
There is a build error:
`C:\projects\system-linq-dynamic-core\src\System.Linq.Dynamic.Core\ExpressionParser.cs(678,44): error CS7036: There is no argument given that corresponds to the required formal parameter 'ignoreCase' of 'Enum.Parse(Type, string, bool)'`

2]
Can you please add/update unit-tests ?

**Comment by jogibear9988** [comment]
Done

**Comment by StefH** [comment]
Enum Parse with 'true' is case sensitive; is that what we want? I think other things are case insensitive?

**Comment by jogibear9988** [comment]
sorry, i wanted to use false.


Von meinem iPhone gesendet

**Comment by StefH** [comment]
Merged and new NuGet created : https://www.nuget.org/packages/System.Linq.Dynamic.Core/1.0.5.2

**Pull request merged**
