### PR TITLE
Fix Guid? == null comparison

### PR DESCRIPTION
**Pull request by jogibear9988**
Can you create a new nuget?

### CODE REVIEW

**Comment by StefH** [comment]
Unit tests fail. Can you take a look at your code?

**Comment by jogibear9988** [comment]
I thought, maybe we should work on 

int FindBestMethod(IEnumerable<MethodBase> methods, Expression[] args, out MethodBase method)
        
the different created arrays seem not verry perfomant to me

**Comment by jogibear9988** [comment]
fixed...

**Comment by jogibear9988** [comment]
would be nice if it could be merged, and you could create a new nuget

**Comment by jogibear9988** [comment]
can you create a new nuget?

**Comment by StefH** [comment]
I did merge, and added some extra tests.

However it some tests fails? Not related to guid I think, maybe I missed something...
See:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs#L583

**Comment by jogibear9988** [comment]
I fixed your test, you need to use 

      new object[] {null}

but there was also a error then in the lib, because the expression is not the same as the cached null expression!

**Pull request merged**
