### PR TITLE
[Fix] Fixed null in Parameter and added functionality Binary And and Or with different Types

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
Maybe this could also be included in the nuget ;-) ?

**Comment by jogibear9988** [comment]
Can this be merged?

**Comment by StefH** [comment]
I provided some code-review comments, can you please fix ?

**Comment by jogibear9988** [comment]
Where? I don't see them!

**Comment by StefH** [comment]
Review is requested now, sorry I did not press the button... ;-)

**Comment by jogibear9988** [comment]
if it's okay, can you merge and create a nuget?

**Comment by StefH** [comment]
1.0.7.2 / 1.0.4.2 added to NuGet

**Pull request merged**
