### PR TITLE
 Fix for ParseLambda with itType and resultType: correct order of arguments

### PR DESCRIPTION
**Pull request by OlegNadymov**
I've created the separate branch for my fix.

### CODE REVIEW

**Comment by StefH** [comment]
OK. I made a small fix to the unit-test and fixed sonarcloud integration.

I can merge this PR to master, however do you also need a new NuGet ?

**Comment by OlegNadymov** [comment]
Yes, I need a new NuGet. Could you do it?

**Comment by StefH** [comment]
NuGet uploaded

**Comment by OlegNadymov** [comment]
@StefH thank you!

**Pull request merged**
