### PR TITLE
[Feature] Usage of cached Lambda Expressions

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by StefH** [comment]
I'll wait wait merge until you are ready...

**Comment by jogibear9988** [comment]
Now I'm ready...

**Comment by jogibear9988** [comment]
I've also fixed that Single and Last did not support querys with parameters!

**Comment by StefH** [comment]
Can you also check if you can fix the code-coverage?

**Comment by jogibear9988** [comment]
done

**Comment by jogibear9988** [comment]
Is it ok so that it can be merged?

**Comment by StefH** [comment]
I'll have a detailed look today.

**Comment by jogibear9988** [comment]
Will you create a new nuget?

**Pull request merged**
